# Generated by Django 3.0.2 on 2020-01-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabinspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=10)),
                ('lotNo', models.IntegerField()),
                ('rollNo', models.IntegerField()),
                ('fabric', models.CharField(max_length=30)),
                ('acceptYards', models.IntegerField()),
                ('acceptMeter', models.IntegerField()),
                ('fWidth', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('sticked', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('deviation', models.IntegerField()),
                ('defect', models.CharField(max_length=64)),
                ('no3', models.IntegerField()),
                ('no36', models.IntegerField()),
                ('no69', models.IntegerField()),
                ('no9', models.IntegerField()),
                ('linearPoints', models.IntegerField()),
                ('hole01', models.IntegerField()),
                ('hole1', models.IntegerField()),
                ('holePoints', models.IntegerField()),
                ('totalPoints', models.IntegerField()),
                ('pointsyards', models.IntegerField()),
                ('pointsperm', models.IntegerField()),
                ('pointspercm', models.IntegerField()),
            ],
        ),
    ]
