# Generated by Django 3.0.2 on 2020-01-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finspectionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabinspection',
            name='acceptance',
            field=models.CharField(default='Y', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabinspection',
            name='grade',
            field=models.CharField(default='A', max_length=2),
            preserve_default=False,
        ),
    ]
